import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  specSidebar: [
    {
      type: "doc",
      id: "spec/index",
      label: "Overview",
    },
    {
      type: "category",
      label: "Structure",
      items: [
        {
          type: "autogenerated",
          dirName: "spec/structure",
        },
      ],
    },
    {
      type: "category",
      label: "Common",
      items: [
        {
          type: "autogenerated",
          dirName: "spec/common",
        },
      ],
    },
    {
      type: "category",
      label: "Implementation",
      items: [
        {
          type: "autogenerated",
          dirName: "spec/implementation",
        },
      ],
    },
    {
      type: "doc",
      id: "spec/license",
      label: "License",
    },
  ],
};

export default sidebars;
